### ISSUE TITLE
Option not to remove fill and stroke properties

### ISSUE THREAD

**Issue by jannicz** [kristoferjoseph/svg-symbols#1]
Running svg-symbols removes the fill and stroke properties while creating the symbols SVG file. This can lead to color loss in the icons, if the project setup relies on this properties.

Suggested solution: would it be possible to pass additional arguments, i.e. `svg-symbols ./directory-of-svgs > ./symbol-file.svg --keep-styles` what would cause the script to preserve the stroke and fill properties? So the script would not run lines 24-26 if the argument is present?!

Lines in the code: https://github.com/kristoferjoseph/svg-symbols/blob/master/index.js#L25 and L26

**Comment by kristoferjoseph** [comment]
Hey, thanks for taking the time to file this issue.
This is working as designed though. 
You can style the output svg with css and there is a handy tool listed in the README that extracts the css needed to do this.

Going to close this issue.
